apiVersion: v1
kind: Service
metadata:
  name: authsvc
spec:
  selector:
    app.kubernetes.io/name: authsvc
  ports:
    - protocol: TCP
      port: 50050
      targetPort: 50050
      name: "grpc-port"
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: "jwk-port"
  type: ClusterIP

