apiVersion: v1
kind: Service
metadata:
  name: authsvc-db
spec:
  selector:
    app.kubernetes.io/name: authsvc-db
  ports:
    - protocol: TCP
      port: 30543
      targetPort: 5432
  type: ClusterIP

