apiVersion: apps/v1
kind: Deployment
metadata:
  name: authsvc
  namespace: default
  labels:
    app: authsvc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authsvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authsvc
    spec:
      containers:
        - name: authsvc
          image: localhost:32000/authsvc:registry
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@authsvc-db:30543/datab'
            - name: SUPERADMIN_EMAIL
              value: "superadmin@surveyx.com"
            - name: SUPERADMIN_PASS
              value: "123456"
          ports:
            - containerPort: 50050
          command: ["/bin/sh","-c"]
          args: ["go run ./cmd/seed/main.go; sleep 10; go run ./cmd/server/main.go"]

      initContainers:
        - name: authsvc-migrate
          image: localhost:32000/authsvc-migrate:registry
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@authsvc-db:30543/datab?sslmode=disable'
          args:
            ['-path', '/tmp', '-database', '$(DATABASE_URL)', '-verbose', 'up']
