apiVersion: apps/v1
kind: Deployment
metadata:
  name: authsvc
  namespace: default
  labels:
    app: authsvc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authsvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authsvc
    spec:
      containers:
        - name: authsvc
          image: localhost:32000/authsvc:registry
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@authsvc-db:30543/datab'
          ports:
            - containerPort: 50050

      initContainers:
        - name: authsvc-migrate
          image: localhost:32000/authsvc-migrate:registry
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@authsvc-db:30543/datab?sslmode=disable'
          args:
            [
              '-path',
              '/tmp',
              '-database',
              '$(DATABASE_URL)',
              '-verbose',
              'up',
            ]
      volumes:
        - name: db-data
          hostPath:
            path: /var/lib/pgdata
            type: DirectoryOrCreate
