apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authsvc-db
  namespace: default
  labels:
    app: authsvc-db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authsvc-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authsvc-db
    spec:
      containers:
        - name: authsvc-db
          image: postgres:15
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: datab
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    '/bin/sh',
                    '-c',
                    'pg_ctl -D /var/lib/authsvc/pgdata -w -t 60 -m fast stop',
                  ]
      volumes:
        - name: db-data
          hostPath:
            path: /var/lib/authsvc/pgdata
            type: DirectoryOrCreate
