apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - surveysvc-db-deploy.yaml
  - surveysvc-db-svc.yaml
  - surveysvc-deploy.yaml
  - surveysvc-svc.yaml 
  - surveysvc-broker-deploy.yaml
  - surveysvc-broker-svc.yaml
  - surveysvc-consumer-deploy.yaml