apiVersion: v1
kind: Service
metadata:
  name: surveysvc
spec:
  selector:
    app.kubernetes.io/name: surveysvc
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
      name: "http-port"
  type: ClusterIP 