apiVersion: v1
kind: Service
metadata:
  name: surveysvc
spec:
  selector:
    app.kubernetes.io/name: surveysvc
    app.kubernetes.io/language: golang
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
      name: "http-port"
    - protocol: TCP
      port: 9464
      targetPort: 9464
      name: '9464'
  type: ClusterIP 