apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveysvc
  namespace: default
  labels:
    app: surveysvc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: surveysvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: surveysvc
    spec:
      containers:
        - name: surveysvc
          image: localhost:32000/surveysvc:registry
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@surveysvc-db:30544/datab'
          ports:
            - containerPort: 50052
              name: "http-port"
          command: ["/bin/sh","-c"]
          args: ["go run ./cmd/server/main.go"]

      initContainers:
        - name: surveysvc-migrate
          image: localhost:32000/surveysvc-migrate:registry
          env:
            - name: DATABASE_URL
              value: 'postgresql://postgres:postgres@surveysvc-db:30544/datab?sslmode=disable'
          args:
            ['-path', '/tmp', '-database', '$(DATABASE_URL)', '-verbose', 'up'] 