apiVersion: v1
kind: Service
metadata:
  name: surveysvc-broker
spec:
  selector:
    app.kubernetes.io/name: surveysvc-broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: '9092'
  type: ClusterIP 