apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: surveysvc-broker
  namespace: default
  labels:
    app: surveysvc-broker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: surveysvc-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: surveysvc-broker
    spec:
      containers:
        - name: surveysvc-broker
          image: apache/kafka:4.0.0
          env:
            - name: KAFKA_NODE_ID
              value: '1'
            - name: KAFKA_PROCESS_ROLES
              value: 'broker,controller'
            - name: KAFKA_LISTENERS
              value: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://surveysvc-broker:9092'
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: '1@surveysvc-broker:9093'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: '1'
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: '1'
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: '0'
            - name: KAFKA_NUM_PARTITIONS
              value: '3'
            - name: CLUSTER_ID
              value: oh-sxaDRTcyAr6pFRbXyzA
          ports:
            - containerPort: 9092
            - containerPort: 9093
          volumeMounts:
            - name: broker-data
              mountPath: /tmp
      volumes:
        - name: broker-data
          emptyDir:
            sizeLimit: 500Mi
