apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat-sa # New ServiceAccount name
  namespace: default # Match your DaemonSet's namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-role # New ClusterRole name
  labels:
    app: filebeat
rules:
  - apiGroups: ['']
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-binding # New ClusterRoleBinding name
subjects:
  - kind: ServiceAccount
    name: filebeat-sa
    namespace: default # Must match ServiceAccount namespace
roleRef:
  kind: ClusterRole
  name: filebeat-role # Must match ClusterRole name
  apiGroup: rbac.authorization.k8s.io
