apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: '4317'
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: '4318'

  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-exp
spec:
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
  type: LoadBalancer