apiVersion: v1
kind: Service
metadata:
  name: kibana-exp
spec:
  selector:
    app.kubernetes.io/name: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: LoadBalancer