apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - elastic-deploy.yaml
  - elastic-svc.yaml
  - jaeger-deploy.yaml
  - jaeger-svc.yaml
  - prometheus-config.yaml
  - prometheus-deploy.yaml
  - prometheus-svc.yaml
  - filebeat-rbac.yaml
  - filebeat-config.yaml
  - filebeat-deploy.yaml
  - kibana-deploy.yaml
  - kibana-svc.yaml
