apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
  namespace: default
  labels:
    app: apigw
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apigw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apigw
    spec:
      containers:
        - name: apigw
          image: devopsfaith/krakend:2.9
          ports:
            - containerPort: 8080
          args: ["run", "-c", "/etc/krakend/krakend.json"]
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend
            - name: krakend-jwk
              mountPath: /etc/krakend/jwk
            - name: krakend-pb
              mountPath: /etc/krakend/pb
              
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
        - name: krakend-jwk
          configMap:
            name: krakend-jwk
        - name: krakend-pb
          hostPath:
            path: /home/zero/Documents/code/surveyx/k8s/apigw/pb/
            type: Directory