apiVersion: v1
kind: Service
metadata:
  name: orgsvc-db
spec:
  selector:
    app.kubernetes.io/name: orgsvc-db
  ports:
    - protocol: TCP
      port: 30542
      targetPort: 5432
  type: ClusterIP

