apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgsvc
  namespace: default
  labels:
    app: orgsvc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orgsvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orgsvc
    spec:
      containers:
        - name: orgsvc
          image: localhost:32000/orgsvc:registry
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: 'postgresql+asyncpg://postgres:postgres@orgsvc-db:30542/datab'
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: 'true'
            - name: OTEL_TRACES_EXPORTER
              value: 'otlp'
            - name: OTEL_METRICS_EXPORTER
              value: 'otlp'
            - name: OTEL_LOGS_EXPORTER
              value: 'console,otlp'
          ports:
            - containerPort: 8000
