apiVersion: v1
kind: Service
metadata:
  name: orgsvc
spec:
  selector:
    app.kubernetes.io/name: orgsvc
    app.kubernetes.io/language: python
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: '8000'
    - protocol: TCP
      port: 9464
      targetPort: 9464
      name: '9464'
  type: ClusterIP